config/urls.py
import sys

from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('diary.urls')),  # 追加：includeメソッドでurl設定を追加
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),

]

# Add debug toolbar if DEBUG is True and not executed by manage.py test command
if settings.DEBUG and 'test' not in sys.argv:
    urlpatterns += path('__debug__/', include('debug_toolbar.urls')),

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

diary/urls.py
from django.urls import path

from . import views

app_name = 'diary'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('index/', views.IndexView.as_view(), name='index'),
    path('diary_create/', views.DiaryCreateView.as_view(), name='diary_create'),
    path('diary_create_complete/', views.DiaryCreateCompleteView.as_view(), name='diary_create_complete'),
    path('diary_list/', views.DiaryListView.as_view(), name='diary_list'),  # 追記
    path('diary_detail/<uuid:pk>/', views.DiaryDetailView.as_view(), name='diary_detail'),  # 追記
    path('diary_update/<uuid:pk>/', views.DiaryUpdateView.as_view(), name='diary_update'),  # 追記
    path('diary_delete/<uuid:pk>/', views.DiaryDeleteView.as_view(), name='diary_delete'),  # 追加
    path('tag/<slug:tag>/', views.DiaryTagView.as_view(), name='diary_tag_list'),
    path('tag/config/list/', views.TagListView.as_view(), name='tag_list'),
    path('tag/config/create/', views.TagCreateView.as_view(), name='tag_create'),
    path('tag/config/update/<int:pk>/', views.TagUpdateView.as_view(), name='tag_update'),
    path('tag/config/delete/<int:pk>/', views.TagDeleteView.as_view(), name='tag_delete'),
    path('comment/<int:pk>/delete/', views.CommentDeleteView.as_view() , name='comment_delete'),
    path('comment/<int:pk>/edit/', views.CommentEditView.as_view(), name='comment_edit'),
]

diary/models.py
import logging
import os
import uuid

import cv2
from django.conf import settings
from django.db import models
from django.shortcuts import resolve_url
from django.urls import reverse
from django.utils import timezone
from imagekit.models import ImageSpecField
from pilkit.processors import ResizeToFill


logger = logging.getLogger(__name__)


class Tag(models.Model):
    """
    Diary につけられるタグ。

    ひとつの Diary に複数つけられる。
    また、同じタグを複数の Diary につけることができる。

    unique=True のものフィールドの値は、同一モデル内で重複できない
    """
    name = models.CharField(max_length=50, unique=True)
    slug = models.SlugField(max_length=50, unique=True)

    def __str__(self):
        return f'{self.name}'

    def get_absolute_url(self):
        return reverse('diary:diary_tag_list', args=[self.slug])


class Diary(models.Model):
    app_label = "diary"
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    date = models.DateField(verbose_name='日付', default=timezone.now)
    title = models.CharField(verbose_name='タイトル', max_length=40)
    text = models.TextField(verbose_name='本文', max_length=2000, blank=True, null=True)
    image = models.ImageField(upload_to='images/', verbose_name='写真', blank=True, null=True)
    image_video = models.ImageField(upload_to='video_images/', verbose_name='動画のサムネイル', blank=True, null=True)
    video = models.FileField(upload_to='videos/', verbose_name='動画', blank=True, null=True)  # 動画用のフィールドを追加

    secret = models.BooleanField(verbose_name='内緒', default=True)
    created_at = models.DateTimeField(verbose_name='作成日時', default=timezone.now)
    updated_at = models.DateTimeField(verbose_name='編集日時', blank=True, null=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, default=None)
    tags = models.ManyToManyField(Tag, blank=True, verbose_name='タグ')
    # thumbnail = ImageSpecField(source='image', processors=[ResizeToFill(200, 200)], format='JPEG', options={'quality': 60}, )
    # thumbnail_video = ImageSpecField(source='image_video', processors=[ResizeToFill(200, 200)], format='JPEG', options={'quality': 60}, )
    # thumbnail_video_detail = ImageSpecField(source='image_video', processors=[ResizeToFill(400, 400)], format='JPEG', options={'quality': 60}, )


    def __str__(self):
        return f"{self.title} - {self.date}"


    def get_absolute_url(self):
        return resolve_url('diary:diary_detail', pk=self.pk)




    def save(self, *args, **kwargs):
        logger.info('Diary.save method called')
        output_folder = os.path.join(settings.MEDIA_ROOT, 'video_images/')
        os.makedirs(output_folder, exist_ok=True)  # フォルダを作成する
        if not self.image and not self.image_video:  # image_video の投稿がない場合のみ実行
            super().save(*args, **kwargs)
            logger.info('Diary.save super().save success')
            if self.video:
                path = self.video.path  # ファイルの保存された場所
                file_name = os.path.basename(path)  # ファイル名部分
                logger.info('Diary.save file_name=%s.', file_name)

                # opencvで1秒地点を読み込む
                cap = cv2.VideoCapture(path)
                logger.info('Diary.save cap created')
                cap.set(cv2.CAP_PROP_POS_MSEC, 1000)
                logger.info('Diary.save set success')
                is_success, image = cap.read()
                logger.info('Diary.save cap.read() is_success=%s.', is_success)

                # 読み込んだ部分を書き出す
                output_path = os.path.join(output_folder, f'{file_name}.jpg')
                cv2.imwrite(output_path, image)
                logger.info('Diary.save output_path output_path=%s.', output_path)

                # 書き出したファイルのパスを、image_videoに格納して保存
                self.image_video.name = f'video_images/{file_name}.jpg'
                self.thumbnail_video.name = f'video_images/{file_name}_thumbnail.jpg'
                self.thumbnail_video_detail.name = f'video_images/{file_name}_detail.jpg'
                logger.info('Diary.save self.image_video.name self.image_video.name=%s.', self.image_video.name)
                logger.info('Diary.save self.thumbnail_video.name self.thumbnail_video.name=%s.', self.thumbnail_video.name)
                logger.info('Diary.save self.thumbnail_video_detail.name self.thumbnail_video_detail.name=%s.', self.thumbnail_video_detail.name)
        # logger.info('Diary.save self.thumbnail.name self.thumbnail.name=%s.', self.thumbnail.name)
        logger.info('Diary.save self.image_video.name self.image_video.name=%s.', self.image_video.name)
        # logger.info('Diary.save self.thumbnail_video.name self.thumbnail_video.name=%s.', self.thumbnail_video.name)
        # logger.info('Diary.save self.thumbnail_video_detail.name self.thumbnail_video_detail.name=%s.', self.thumbnail_video_detail.name)
        super().save(*args, **kwargs)
        logger.info('diary save end')






class Comment(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    created_at = models.DateTimeField(verbose_name='作成日時', default=timezone.now)
    text = models.TextField(verbose_name='コメント', max_length=500, blank=True)
    diary = models.ForeignKey(Diary, on_delete=models.CASCADE)

    def get_absolute_url(self):
        return resolve_url('diary:diary_detail', pk=self.diary.pk)

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="jp">
    {% load django_bootstrap5 %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}

    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {#    <script src="https://kit.fontawesome.com/8e8ea8fb7e.js" crossorigin="anonymous"></script>#}
        <script src="{% static 'fontawesome-free-6.4.0-web/js/all.js' %}"></script>
        {% block extra_js %}{% endblock %}
        <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
        {% block extra_css %}{% endblock %}
        <title>{% block title %}{% endblock %}</title>
    </head>
    <body>
        <main class="container">
            {% block breadcrumb %}{% endblock %}
            {% bootstrap_messages %}
            <h1 class="h1_header">{% block header_h1 %}{% endblock %}</h1>
            <div class="justify-content-center">
                {% block main_content %}{% endblock %}
            </div>
        </main>
        {% block extra_footer_js %}{% endblock %}
    </body>
</html>

templates/comment_delete.html
{% extends "base.html" %}
{% load django_bootstrap5 %}

{% block title %}
    コメント削除 - {{ block.super }}
{% endblock %}

{% block header_h1 %}
    コメント削除
{% endblock %}

{% block breadcrumb %}
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container-fluid">
        <a class="navbar-brand" href="#">育児日記</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item">
              <a class="nav-link" aria-current="page" href="{% url 'diary:index' %}"><i class="fas fa-home"></i> ホーム</a>
            </li>
            {% if request.user.is_staff %}
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'diary:tag_list' %}"><i class="fas fa-tags"></i> タグ一覧</a>
                </li>
            {% endif %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'diary:diary_list' %}"><i class="fas fa-book"></i> 日記一覧</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{{ comment.get_absolute_url }}"><i class="fas fa-book"></i> 日記詳細</a>
            </li>
            <li class="nav-item">
              <a class="nav-link active"><i class="fas fa-trash-alt"></i> コメント削除</a>
            </li>
          </ul>
          <ul class="navbar-nav ms-auto">
            {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'logout' %}">ログアウト</a>
                </li>
            {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'login' %}"></i>ログイン</a>
                </li>
            {% endif %}
          </ul>
        </div>
      </div>
    </nav>
{% endblock %}

{% block main_content %}

    <form method="post">
      {% csrf_token %}
      <input type="hidden" name="confirm_delete" value="1">
      <p>本当に削除してもよろしいですか？</p>
      <button type="submit" class="btn btn-danger">はい</button>
      <input type="hidden" name="confirm_delete" value="1">
      <a href="{{ comment.get_absolute_url }}" class="btn btn-primary">いいえ</a>
    </form>

{% endblock %}

templates/diary_detail.html
{% extends "base.html" %}

{% block title %}
    {{ diary.title }} - {{ block.super }}
{% endblock %}

{% block header_h1 %}
    <div class="card-header">
        <div class="tag-container">
            {% for tag in object.tags.all %}
                <a href="{{ tag.get_absolute_url }}" class="noborder badge bg-info text-wrap">{{ tag.name }}</a>
            {% endfor %}
        </div>
        <div>
            <h1>{{ diary.title }}</h1>
        </div>
        <div class="mb-3"></div>  {# スペースを追加する行 #}
    </div>
{% endblock %}

{% block breadcrumb %}
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container-fluid">
        <a class="navbar-brand" href="#">育児日記</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="true" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item">
              <a class="nav-link" aria-current="page" href="{% url 'diary:index' %}"><i class="fas fa-home"></i> ホーム</a>
            </li>
            {% if request.user.is_staff %}
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'diary:tag_list' %}"><i class="fas fa-tags"></i> タグ一覧</a>
                </li>
            {% endif %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'diary:diary_list' %}"><i class="fas fa-book"></i> 日記一覧</a>
            </li>
            <li class="nav-item">
              <a class="nav-link active"><i class="far fa-file-alt"></i> 日記詳細</a>
            </li>
          </ul>
          <ul class="navbar-nav ms-auto">
            {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'logout' %}">ログアウト</a>
                </li>
            {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'login' %}"></i>ログイン</a>
                </li>
            {% endif %}
          </ul>
        </div>
      </div>
    </nav>
{% endblock %}

{% block main_content %}
{#    <p>#}
{#        {% for tag in object.tags.all %}#}
{#             <a href="{{ tag.get_absolute_url }}" class="noborder badge bg-info text-wrap">{{ tag.name }}</a>#}
{#        {% endfor %}#}
{#    </p>#}

    <div class="card">
        <div class="card-header">
            <small class="text-muted">{{ diary.date|date:"Y年m月d日(D)" }}</small>
            <small class="text-muted"> {{ diary.user }}</small>
        </div>
        {% if diary.image %}
            <img src="{{ diary.image.url }}" class="card-img-top" alt="{{ diary.title }}">
        {% endif %}
        {% if object.video %}
     	    <div class="ratio ratio-1x1">
                <video controls poster="{{diary.image_video.url}}">
                    <source src="{{ object.video.url }}" type="video/mp4">
                        このブラウザはビデオタグをサポートしていません。
                </video>
            </div>
        {% endif %}
        <div class="card-body">
            <p class="card-text">{{ diary.text|linebreaksbr }}</p>
        </div>
        {% if request.user.is_staff or request.user == diary.user %}
            <div class="article-control-area">
                <a href="{% url 'diary:diary_update' diary.pk %}" class="btn btn-primary">編集</a>
                <a href="{% url 'diary:diary_delete' diary.pk %}" class="btn btn-danger">削除</a>
            </div>
        {% endif %}
    </div>
    <br>
    <a href="javascript:history.back()" class="btn btn btn-success"><i class="fas fa-chevron-left"></i> 戻る</a>

    <h2 class="mt-5">コメント</h2>
    <hr>

    {% if request.user.is_authenticated %}
        <form method="POST" action="">
            {% csrf_token %}
            <div class="mb-3">
                <label for="comment-text" class="form-label">コメントする</label>
                <textarea class="form-control" id="comment-text" name="text" rows="3" required></textarea>
            </div>
            <button type="submit" class="btn btn-primary">コメントする</button>
        </form>
    {% endif %}

    <div class="mt-5">
        {% if object.comment_set.all %}
            {% for comment in object.comment_set.all %}
                <div class="card mb-3">
                    <div class="card-header nowrap">
                        <h5 class="card-title d-inline">{{ comment.user }} </h5>
                        <small class="text-muted"> {{ comment.created_at|date:"Y年n月j日(D) G:i" }}</small>
                        {% if request.user == comment.user %}
                            <a href="{% url 'diary:comment_edit' comment.pk %}" class="btn btn-light"><i class="fas fa-edit"></i></a>
                        {% endif %}
                        {% if request.user.is_staff or request.user == comment.user %}
                             <a href="{% url 'diary:comment_delete' comment.pk %}" class="btn btn-light"><i class="fas fa-trash-alt"></i></a>
                        {% endif %}
                    </div>
                    <div class="card-body">
                        <p class="card-text">{{ comment.text|linebreaksbr }}</p>
                    </div>
                </div>
            {% endfor %}

        {% else %}
            <p>コメントはありません。</p>
        {% endif %}
    </div>


{% endblock %}

templates/diary_list.html
{% extends "base.html" %}

{% block title %}
    日記一覧 - {{ block.super }}
{% endblock %}

{% block header_h1 %}
{#    <br>#}
    日記一覧
{% endblock %}

{% block breadcrumb %}
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container-fluid">
        <a class="navbar-brand" href="#">育児日記</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item">
              <a class="nav-link" aria-current="page" href="{% url 'diary:index' %}"><i class="fas fa-home"></i> ホーム</a>
            </li>
            {% if request.user.is_staff %}
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'diary:tag_list' %}"><i class="fas fa-tags"></i> タグ一覧</a>
                </li>
            {% endif %}
            <li class="nav-item">
              <a class="nav-link" active　href="{% url 'diary:diary_list' %}"><i class="fas fa-book"></i> 日記一覧</a>
            </li>
          </ul>
          <ul class="navbar-nav ms-auto">
            {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'logout' %}">ログアウト</a>
                </li>
            {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'login' %}"></i>ログイン</a>
                </li>
            {% endif %}
          </ul>
        </div>
      </div>
    </nav>

{% endblock %}

{% block main_content %}
{#    <hr>#}
    <div class="my-3">
        <a href="{% url 'diary:diary_create' %}" class="btn btn-success">新規作成</a>
    </div>
            <h1>{{ tag.name }}</h1>

    <form method="GET" action="{% url 'diary:diary_list' %}">
        <div class="form-row">
            <div class="form-group col-md-4">
                <label for="tag" class="bg-light"><strong>タグで絞りこみ：</strong></label>
                <select name="tag" id="tag" class="form-control">
                    <option value="">すべて</option>
                    {% for tag in tags %}
                        <option value="{{ tag.slug }}"
                                {% if tag.slug == selected_tag %} selected {% endif %}>
                            {{ tag.name }}
                        </option>
                    {% endfor %}
                </select>
            </div>
            <div class="form-group col-md-4">
                <label for="keyword" class="bg-light"><strong>キーワードで絞りこみ：</strong></label>
            </div>
            <div class="form-group col-md-4 position-relative">
                <input type="text" name="keyword" value="{{ keyword }}" class="form-control pl-4 custom-placeholder" placeholder="日付/タイトル/本文/ユーザー名で検索">
                    <span class="position-absolute top-50 end-0 translate-middle-y p-2" style="transform: translateY(50%);">
                    <i class="fas fa-search search-icon"></i>
                </span>
            </div>

            <div class="form-group col-md-4">
                <label for="num_diaries" class="bg-light"><strong>1ページあたりの日記の表示数：</strong></label>
                <select name="num_diaries" id="num_diaries" class="form-control">
                    <option value="1" {% if num_diaries == '1' %} selected {% endif %}>1</option>
                    <option value="6" {% if num_diaries == '6' %} selected {% endif %}>6</option>
                    <option value="8" {% if num_diaries == '8' %} selected {% endif %}>8</option>
                    <option value="10" {% if num_diaries == '10' %} selected {% endif %}>10</option>
                    <option value="20" {% if num_diaries == '20' %} selected {% endif %}>20</option>
                    <option value="30" {% if num_diaries == '30' %} selected {% endif %}>30</option>
                    <option value="all" {% if num_diaries == 'all' %} selected {% endif %}>すべて</option>
                </select>
            </div>
            <div class="form-group col-md-4">
                <label for="order_by" class="bg-light"><strong>表示順：</strong></label>
              <select name="order_by" id="order_by" class="form-control">
                <option value="-date" {% if order_by == '-date' %} selected {% endif %}>新しい順</option>
                <option value="date" {% if order_by == 'date' %} selected {% endif %}>古い順</option>
              </select>
            </div>
        </div>
        <button type="submit" class="btn btn-success"><i class="fas fa-refresh"></i></button>

    </form>
    <br>
    <div class="row row-cols-1 row-cols-md-2 g-4">
        {% if diary_list %}
            {% for diary in diary_list %}

                <div class="col">
                    <div class="card">
                        <div class="card-body">
                            <h5 class="card-title">{{ diary.title }}</h5>
                            {% if diary.image %}
                                <img src="{{ diary.image.url }}" class="img-fluid">
                            {% elif diary.image_video %}
                                <img src="{{ diary.image_video.url }}" class="img-fluid">
    {#                        {% elif diary.image_video %}#}
    {#                            <img src="{{ diary.image_video.url }}" class="img-fluid thumnail">#}
                            {% endif %}
                            <p class="card-text">{{ diary.text|truncatechars:50 }}</p>
    {#                        <a href="{% url 'diary:diary_detail' diary.pk %}" class="btn btn-primary">詳細を見る</a>#}
                            <a href="{{diary.get_absolute_url}}" class="btn btn-primary">詳細を見る</a>
                        </div>
                        <div class="card-footer">
                            <small class="text-muted">{{ diary.date|date:"Y年m月d日(D)" }} {{ diary.user }}</small>
                        </div>
                    </div>
                </div>

            {% endfor %}
        {% else %}
{#            <div class="col">#}
{#                <div class="card">#}
{#                    <div class="card-body">#}
                        <p class="card-text">日記はまだありません。</p>
{#                    </div>#}
{#                </div>#}
{#            </div>#}
        {% endif %}
    </div>

    <br>
    {% if is_paginated %}
        <nav aria-label="Page navigation">
          <ul class="pagination justify-content-center overflow-auto" style="white-space: nowrap">
            {% if page_obj.has_previous %}
                <li class="page-item">
                  <a class="page-link" href="?page={{ page_obj.previous_page_number }}{% if selected_tag %}&tag={{ selected_tag }}{% endif %}{% if keyword %}&keyword={{ keyword }}{% endif %}{% if num_diaries %}&num_diaries={{ num_diaries }}{% endif %}{% if order_by %}&order_by={{ order_by }}{% endif %}" aria-label="previous">
                    <strong><<</strong>
                  </a>
                </li>
            {% endif %}
            {% for page_num in paginator_range %}
                  {% if page_num == paginator.ELLIPSIS %}
                    <li class="page-item disabled"><span class="page-link">{{ page_num }}</span></li>
                  {% elif page_obj.number|add:-1 <= page_num and page_num <= page_obj.number|add:1 %}
                    {% if page_obj.number == page_num %}
                      <li class="page-item active">
                        <span class="page-link">{{ page_num }}<span class="sr-only">(current)</span></span>
                      </li>
                    {% else %}
                      <li class="page-item">
                        <a class="page-link" href="?page={{ page_num }}{% if selected_tag %}&tag={{ selected_tag }}{% endif %}{% if keyword %}&keyword={{ keyword }}{% endif %}{% if num_diaries %}&num_diaries={{ num_diaries }}{% endif %}{% if order_by %}&order_by={{ order_by }}{% endif %}">
                          {{ page_num }}
                        </a>
                      </li>
                    {% endif %}
                  {% elif page_num == 1 or page_num == paginator.num_pages %}
                    <li class="page-item">
                      <a class="page-link" href="?page={{ page_num }}{% if selected_tag %}&tag={{ selected_tag }}{% endif %}{% if keyword %}&keyword={{ keyword }}{% endif %}{% if num_diaries %}&num_diaries={{ num_diaries }}{% endif %}{% if order_by %}&order_by={{ order_by }}{% endif %}">
                        {{ page_num }}
                      </a>
                    </li>
                  {% endif %}
            {% endfor %}
            {% if page_obj.has_next %}
                <li class="page-item">
                  <a class="page-link" href="?page={{ page_obj.next_page_number }}{% if selected_tag %}&tag={{ selected_tag }}{% endif %}{% if keyword %}&keyword={{ keyword }}{% endif %}{% if num_diaries %}&num_diaries={{ num_diaries }}{% endif %}{% if order_by %}&order_by={{ order_by }}{% endif %}" aria-label="next">
                    <strong>>></strong>
                  </a>
                </li>
            {% endif %}
          </ul>
	  <br>
	  <br>
        </nav>
    {% endif %}

{% endblock %}

templates/tag_list.html
{% extends "base.html" %}

{% block title %}
    タグ一覧 - {{ block.super }}
{% endblock %}

{% block header_h1 %}
    タグ一覧
{% endblock %}

{% block breadcrumb %}
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container-fluid">
        <a class="navbar-brand" href="#">育児日記</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item">
              <a class="nav-link" aria-current="page" href="{% url 'diary:index' %}"><i class="fas fa-home"></i> ホーム</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'diary:diary_list' %}"><i class="fas fa-book"></i> 日記一覧</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" active　href="{% url 'diary:tag_list' %}"><i class="fas fa-tags"></i> タグ一覧</a>
            </li>
          </ul>
          <ul class="navbar-nav ms-auto">
            {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'logout' %}">ログアウト</a>
                </li>
            {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'login' %}"></i>ログイン</a>
                </li>
            {% endif %}
          </ul>
        </div>
      </div>
    </nav>
{% endblock %}

{% block main_content %}
    <a href="{% url 'diary:tag_create' %}" class="btn btn-success"><i class="fas fa-plus"></i> タグを追加</a>
    <table class="table">
        <thead>
        <tr>
            <th>#</th>
            <th>タグ名</th>
            <th>slug</th>
            <th></th>
        </tr>
        </thead>
        <tbody>
        {% for tag in tags %}
            <tr>
                <td>{{ forloop.counter }}</td>
                <td>{{ tag.name }}</td>
                <td>{{ tag.slug }}</td>
                <td>
                    <a href="{% url 'diary:tag_update' tag.pk %}" class="btn btn-primary"><i class="fas fa-edit"></i> </a>
                    <a href="{% url 'diary:tag_delete' tag.pk %}" class="btn btn-danger"><i class="fas fa-trash-alt"></i> </a>
                </td>
            </tr>
        {% empty %}
            <tr>
                <td colspan="5">タグはありません。</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}